### ISSUE TITLE
'NoneType' object has no attribute 'findAll' - Error on importing mht

### ISSUE THREAD

**Issue by annargrs** [tmpethick/anki-onenote-importer#1]
Tested in Windows 10 and Ubuntu 16.10, 64bit, addon installed from anki system.
Failed file is here: https://www.dropbox.com/s/eh14rk7nmwqd3yl/Test%20import.mht?dl=0

Traceback (most recent call last):
  File "C:\Users\username\Documents\Anki\addons\onenote_importer__init__.py", line 66, in importMHT
    output = parser.run()
  File "C:\Users\username\Documents\Anki\addons\onenote_importer\parser.py", line 70, in run
    for row in table.findAll('tr'):
AttributeError: 'NoneType' object has no attribute 'findAll'

**Comment by annargrs** [comment]
Ok, issue solved - it is OneNote's fault. It outputs text and images in tables as text and images, but if there is inking on page, it all becomes an ungodly non-html mess.

**Comment by Spearman17** [comment]
I am still having the same issue but I have no inking on page
