### ISSUE TITLE
index out of range / nested tables

### ISSUE THREAD

**Issue by kapurp** [tmpethick/anki-onenote-importer#2]
when a question has a large table as an answer the following error is generated

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\....\Anki\addons\onenote_importer\__init__.py", line 66, in importMHT
    output = parser.run()
  File "C:\....\Anki\addons\onenote_importer\parser.py", line 73, in run
    answer = self._strip_newlines(tds[1].renderContents())
IndexError: list index out of range

**Comment by kapurp** [comment]
More error testing. Seems to happen if the two by two (col 1 = question, col 2 = answer) table contains further nested table? For example if the answer is itself a 2x2 table.

**Comment by tmpethick** [comment]
@kapurp Sorry, I've been rather busy lately. I've finally got around to make the changes I think should fix it and have updated it on [anki add-ons](https://ankiweb.net/shared/info/1971641744). Please write me if you are still having troubles.

Thanks for the feedback!
