### ISSUE TITLE
multiple tables

### ISSUE THREAD

**Issue by ghost** [tmpethick/anki-onenote-importer#3]
using mac version

if I have 2 or more seperate tables on the one MHT page, only the first table is imported.. all subsequence tables are ignored

im not good at PR but its an easy fix

I also give my tables a title that I want anki to add from, and ignore all other tables, because some tables are for other things more than study cards

```
       for table in self.soup.findAll('table'):
            repElemID = table.get('title')
            if repElemID == 'anki':
                for row in table.findAll('tr', recursive=False):
                    tds = [td for td in row.findAll(recursive=False, limit=2)]
                    question = self._strip_newlines(tds[0].renderContents())
                    answer = self._strip_newlines(tds[1].renderContents())
                    output += '%s\t%s\n' % (question, answer)
        return output
```

might help others out there.. I'm also looking into testing for blank lines to skip from adding, and rows that don't include text in either the Q or A column

**Comment by Ziinc** [comment]
Should be noted that not everyone will have the same workflow. Might be better to make the "anki" flag optional for flagging table imports.

How exactly do you create a table title?

I've made a PR for the multiple table import

**Comment by tmpethick** [comment]
I have now merged it, even if it took some time to spot it.. Thanks!
