### ISSUE TITLE
Download Fail

### ISSUE THREAD

**Issue by ninjasul** [tmpethick/anki-onenote-importer#6]
I've tried to download the onenote importer but failed with this message

![image](https://user-images.githubusercontent.com/5219349/37506567-c286855a-292d-11e8-8109-68fd27138978.png)

Could you let me know how to solve this problem?

Thanks.

**Comment by Ziinc** [comment]
Hi ninjasul, this appears to be an issue with your connection when
downloading the plugin from ankiweb. You should either try to install it
again, or try to reinstall anki, or copy and paste the scripts manually
into the plugin folder.

**Comment by tmpethick** [comment]
hmm it is not possible for me to replicate it with the newest version of Anki (v2.0.50 as of writing). What version are you running?

**Comment by ninjasul** [comment]
I used 2.0.50 on windows 10. It's my laptop in the office.
I think my company blocked the HTTPS connection with the Anki update site.
I successfully downloaded with my personal computer. 

Thanks.
