### ISSUE TITLE
Compatibility problem with Anki 2.1.x

### ISSUE THREAD

**Issue by Aster-the-Med-Stu** [tmpethick/anki-onenote-importer#9]
I cannot install this, as it seems that the plugin is released for 2.0.x....

https://ankiweb.net/shared/info/1971641744

**Comment by tmpethick** [comment]
Yeah, sorry I don't have time to maintain it. I suggest downloading anki 2.0 and using the plugin through it. Your anki deck should be compatible to both version simultaneously. 

Happy new year!

**Comment by Aster-the-Med-Stu** [comment]
@tmpethick Oh that's fine! Thanks for your work and happy new year~~
